# Knowing when to use multiple linear regression

Import libries

In [201]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

Loading the dataset

In [202]:
df=pd.read_csv(".\\Data.csv")
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [203]:
y=y.reshape(len(y),1)
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

Splitting the datase into training and testing set

In [204]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

Training the multile liner regression on a trainig set

In [205]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

Predicting the test set result

In [206]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[432.77 430.29]
 [481.2  484.45]
 [470.44 472.16]
 ...
 [450.85 443.48]
 [457.87 458.62]
 [447.57 443.31]]


Evaluating the model performance


In [207]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9312204069568119

# Polynomial Regression

 Importing libraries

In [208]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

Loading a dataset

In [209]:
df=pd.read_csv(".\\Data.csv")
x2=df.iloc[:,:-1].values
y2=df.iloc[:,-1].values

Splitting the data into the traing set and test set

In [210]:
from sklearn.model_selection import train_test_split
x_train2,x_test2,y_train2,y_test2=train_test_split(x2,y2,test_size=0.2,random_state=40)

Training the Polynomial regression model in the training set

In [211]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x_train2)
regressor=LinearRegression()
regressor.fit(x_poly,y_train2)

LinearRegression()

Predicting the test results

In [212]:
y_pred=regressor.predict(poly_reg.transform(x_test2))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test2),1)),1))

[[434.38 430.29]
 [483.18 484.45]
 [474.69 472.16]
 ...
 [449.35 443.48]
 [456.24 458.62]
 [447.52 443.31]]


Evaluating the model performance

In [213]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9444132402353275

# Support Vector Regression

Feature Scaling

In [214]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x_train=sc_x.fit_transform(x_train)
y_train=sc_y.fit_transform(y_train)

Training the SVR model on the Training set

In [215]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(x_train,y_train)

c:\Users\Administrator\Downloads\anaconda4\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting the test set results

In [216]:
y_pred=sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[432.55 430.29]
 [483.84 484.45]
 [474.5  472.16]
 ...
 [448.26 443.48]
 [455.32 458.62]
 [447.99 443.31]]


Evaluating the model performance

In [217]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9478168228458457

# Decision Tree Regression


Training the Decision Tree on the Test Set

In [218]:
from sklearn.tree import DecisionTreeRegressor
regressor=  DecisionTreeRegressor(random_state=0)
regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=0)

Predicting the Test Set results

In [219]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ -1.33 430.29]
 [ -1.33 484.45]
 [ -1.33 472.16]
 ...
 [ -1.33 443.48]
 [ -1.33 458.62]
 [ -1.33 443.31]]


Evaluating the model performance

In [220]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-723.1289865924363

# Random Forest Regression 


Trainign Random Forest Regression Model on Training Set

In [221]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(x_train,y_train)

c:\Users\Administrator\Downloads\anaconda4\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

Predicting the Test Set results

In [222]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ -1.25 430.29]
 [ -1.25 484.45]
 [ -1.25 472.16]
 ...
 [ -1.25 443.48]
 [ -1.25 458.62]
 [ -1.25 443.31]]


Evaluating the model performance

In [223]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-722.8846763488268